import type {
  LifePlanningArea,
  LifePlanningGoal,
  LifePlanningTask,
  ScoreBreakdown,
} from "./prioritizer.js";

const DAY_MS = 24 * 60 * 60 * 1000;
const MAX_VISUAL_INDENT = 3;

const STATUS_ICON: Record<string, string> = {
  open: "[ ]",
  in_progress: "[~]",
  blocked: "[!]",
  done: "[x]",
  cancelled: "[-]",
};

export interface LifePlanningProjectionArea extends LifePlanningArea {
  id: string;
  name: string;
  slug: string;
  cadenceTarget: string | null;
}

export interface LifePlanningProjectionGoal extends LifePlanningGoal {
  id: string;
  areaId: string;
  title: string;
  description: string | null;
  horizon: string | null;
  status: string;
}

export interface LifePlanningProjectionProject {
  id: string;
  areaId: string | null;
  goalId: string | null;
  title: string;
  description: string | null;
  status: string;
}

export interface LifePlanningProjectionTask extends LifePlanningTask {
  id: string;
  title: string;
  areaId: string | null;
  goalId: string | null;
  projectId: string | null;
  parentTaskId: string | null;
  successCriteria: string | null;
  completionMode: string;
  completedAt: number | null;
  updatedAt: number;
}

export interface LifePlanningRankedTask {
  task: LifePlanningProjectionTask;
  goal: LifePlanningProjectionGoal | null;
  area: LifePlanningProjectionArea | null;
  score: ScoreBreakdown;
}

export interface LifePlanningProjectionInput {
  areas: LifePlanningProjectionArea[];
  goals: LifePlanningProjectionGoal[];
  projects: LifePlanningProjectionProject[];
  tasks: LifePlanningProjectionTask[];
  next: LifePlanningRankedTask[];
  now: number;
  sourceLabel: string;
}

/**
 * Render the bundled `_life` planning surface from structural read models.
 *
 * This is a pure projection: it has no database, filesystem, kernel schema or
 * current-time dependency. Hosts must load data and supply `now` explicitly.
 */
export function renderLifePlanningMarkdown(
  input: LifePlanningProjectionInput,
): string {
  const { areas, goals, projects, tasks, next, now, sourceLabel } = input;
  const out: string[] = [];

  out.push(`<!-- AUTO-GENERATED by tasq — DO NOT EDIT. Source of truth: ${sourceLabel} -->`);
  out.push("<!-- Use the `tasq` CLI (or an agent via SKILL.md) to mutate. -->");
  out.push(`<!-- Regenerated: ${new Date(now).toISOString()} -->`);
  out.push("");
  out.push("# TASKS.md — Active tasks (projection of tasq)");
  out.push("");

  if (next.length > 0) {
    out.push("## 🎯 Top priorities (next-action)");
    out.push("");
    next.forEach((ranked, index) => {
      const tags: string[] = [];
      if (ranked.area) tags.push(`#${ranked.area.slug}`);
      if (ranked.goal) tags.push(`@${truncate(ranked.goal.title, 30)}`);
      const tagStr = tags.length ? ` _${tags.join(" ")}_` : "";
      const dueStr = ranked.task.dueAt != null
        ? ` ⏰ ${formatRelative(ranked.task.dueAt, now)}`
        : "";

      out.push(
        `${index + 1}. ${STATUS_ICON[ranked.task.status] ?? "[ ]"} **${ranked.task.title}**${tagStr}${dueStr}`,
      );
      if (ranked.task.nextAction) out.push(`   → ${ranked.task.nextAction}`);
      out.push(
        `   _score ${ranked.score.total.toFixed(2)} (lev ${ranked.score.leverage} · urg ${ranked.score.urgency} · av ${ranked.score.avoidance})_  \`${shortDisplayId(ranked.task.id)}\``,
      );
      out.push("");
    });
  }

  const areasSorted = [...areas].sort((a, b) =>
    b.importance !== a.importance
      ? b.importance - a.importance
      : a.name.localeCompare(b.name),
  );

  for (const area of areasSorted) {
    const goalsInArea = goals.filter(
      (goal) => goal.areaId === area.id && goal.status === "active",
    );
    const projectsInArea = projects.filter(
      (project) =>
        project.areaId === area.id &&
        project.status !== "cancelled" &&
        project.status !== "done",
    );
    const tasksInArea = tasks.filter(
      (task) =>
        task.areaId === area.id &&
        task.status !== "done" &&
        task.status !== "cancelled",
    );

    if (
      goalsInArea.length === 0 &&
      projectsInArea.length === 0 &&
      tasksInArea.length === 0
    ) {
      continue;
    }

    const summary = formatStatusCounts(countByStatus(tasksInArea));
    out.push(
      `## ${area.name} (#${area.slug}, importance ${area.importance})${summary}`,
    );
    if (area.cadenceTarget) {
      out.push(`_cadence: ${area.cadenceTarget} (advisory)_`);
    }
    out.push("");

    for (const goal of goalsInArea) {
      out.push(`### 🎯 ${goal.title}${goal.horizon ? ` _(${goal.horizon})_` : ""}`);
      if (goal.description) out.push(goal.description);
      out.push("");

      const goalProjects = projectsInArea.filter(
        (project) => project.goalId === goal.id,
      );
      for (const project of goalProjects) {
        renderProject(
          out,
          project,
          tasksInArea.filter((task) => task.projectId === project.id),
          now,
        );
      }

      const looseTasks = tasksInArea.filter(
        (task) => task.goalId === goal.id && task.projectId == null,
      );
      if (looseTasks.length > 0) {
        out.push("**Loose tasks (no project)**");
        renderTaskList(out, looseTasks, now);
      }
    }

    const orphanProjects = projectsInArea.filter(
      (project) => project.goalId == null,
    );
    for (const project of orphanProjects) {
      renderProject(
        out,
        project,
        tasksInArea.filter((task) => task.projectId === project.id),
        now,
      );
    }

    const orphanTasks = tasksInArea.filter(
      (task) => task.goalId == null && task.projectId == null,
    );
    if (orphanTasks.length > 0) {
      out.push("### 📋 Tasks (no goal, no project)");
      renderTaskList(out, orphanTasks, now);
    }
  }

  const inbox = tasks.filter(
    (task) =>
      task.areaId == null &&
      task.status !== "done" &&
      task.status !== "cancelled",
  );
  if (inbox.length > 0) {
    out.push("## 📥 Inbox (no area assigned)");
    out.push("");
    renderTaskList(out, inbox, now);
  }

  const recentlyClosed = tasks
    .filter(
      (task) =>
        (task.status === "done" || task.status === "cancelled") &&
        now - (task.completedAt ?? task.updatedAt) < 30 * DAY_MS,
    )
    .sort(
      (a, b) =>
        (b.completedAt ?? b.updatedAt) - (a.completedAt ?? a.updatedAt),
    );

  if (recentlyClosed.length > 0) {
    out.push("");
    out.push("## ✓ Closed in last 30 days");
    out.push("");
    for (const task of recentlyClosed) {
      const closedAt = task.completedAt ?? task.updatedAt;
      out.push(
        `- ${STATUS_ICON[task.status]} ${task.title}  _${formatRelative(closedAt, now)}_`,
      );
    }
  }

  out.push("");
  return out.join("\n");
}

function renderProject(
  out: string[],
  project: LifePlanningProjectionProject,
  projectTasks: LifePlanningProjectionTask[],
  now: number,
): void {
  const summary = formatStatusCounts(countByStatus(projectTasks));
  const progress = formatProgressBadge(projectTasks);
  const statusBadge = project.status !== "active" ? ` _(${project.status})_` : "";
  out.push(`### 📂 ${project.title}${statusBadge}${summary}${progress}`);
  if (project.description) out.push(project.description);
  if (projectTasks.length > 0) {
    renderTaskList(out, projectTasks, now);
  } else {
    out.push("_no active tasks_");
    out.push("");
  }
}

function renderTaskList(
  out: string[],
  tasks: LifePlanningProjectionTask[],
  now: number,
): void {
  const byParent = new Map<string | null, LifePlanningProjectionTask[]>();
  const idsInSlice = new Set(tasks.map((task) => task.id));
  for (const task of tasks) {
    const key =
      task.parentTaskId != null && idsInSlice.has(task.parentTaskId)
        ? task.parentTaskId
        : null;
    const bucket = byParent.get(key) ?? [];
    bucket.push(task);
    byParent.set(key, bucket);
  }

  const roots = (byParent.get(null) ?? []).slice();
  sortTasks(roots);

  const writeTask = (task: LifePlanningProjectionTask, depth: number): void => {
    const icon = STATUS_ICON[task.status] ?? "[ ]";
    const due = task.dueAt != null ? ` ⏰ ${formatRelative(task.dueAt, now)}` : "";
    const recurrence = task.recurrence != null
      ? ` ♻ ${task.recurrenceInterval > 1 ? `${task.recurrenceInterval}×` : ""}${task.recurrence}${task.streak > 0 ? ` (streak ${task.streak})` : ""}`
      : "";
    const childrenInSlice = byParent.get(task.id) ?? [];
    const indent = "  ".repeat(Math.min(depth, MAX_VISUAL_INDENT));
    const overDepth = depth > MAX_VISUAL_INDENT ? " ↳" : "";
    const childCount = childrenInSlice.length > 0
      ? ` _(${childrenInSlice.filter((child) => child.status === "done").length}/${childrenInSlice.length})_`
      : "";

    out.push(
      `${indent}- ${icon}${overDepth} ${task.title}${due}${recurrence}${childCount}  \`${shortDisplayId(task.id)}\``,
    );
    if (
      task.nextAction &&
      (task.status === "open" ||
        task.status === "in_progress" ||
        task.status === "blocked")
    ) {
      out.push(`${indent}  → ${task.nextAction}`);
    }
    if (task.successCriteria) {
      const marker = task.completionMode === "evidence"
        ? "✓ evidence required: "
        : "✓ done when: ";
      out.push(`${indent}  ${marker}${task.successCriteria}`);
    }

    sortTasks(childrenInSlice);
    for (const child of childrenInSlice) writeTask(child, depth + 1);
  };

  for (const root of roots) writeTask(root, 0);
  out.push("");
}

function sortTasks(tasks: LifePlanningProjectionTask[]): void {
  tasks.sort((a, b) => {
    const order = { in_progress: 0, open: 1, blocked: 2, done: 3, cancelled: 4 };
    const aOrder = order[a.status as keyof typeof order] ?? 5;
    const bOrder = order[b.status as keyof typeof order] ?? 5;
    if (aOrder !== bOrder) return aOrder - bOrder;
    const aPriority = a.priority ?? 3;
    const bPriority = b.priority ?? 3;
    if (aPriority !== bPriority) return bPriority - aPriority;
    return a.createdAt - b.createdAt;
  });
}

function formatProgressBadge(
  tasks: readonly LifePlanningProjectionTask[],
): string {
  let done = 0;
  let denominator = 0;
  for (const task of tasks) {
    if (task.status === "cancelled") continue;
    denominator++;
    if (task.status === "done") done++;
  }
  if (denominator === 0) return "";
  const percentage = Math.round((done / denominator) * 100);
  return ` · _${done}/${denominator} done (${percentage}%)_`;
}

function countByStatus(
  tasks: LifePlanningProjectionTask[],
): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const task of tasks) counts[task.status] = (counts[task.status] ?? 0) + 1;
  return counts;
}

function formatStatusCounts(counts: Record<string, number>): string {
  const parts: string[] = [];
  if (counts.in_progress) parts.push(`🔵 ${counts.in_progress}`);
  if (counts.open) parts.push(`⚪ ${counts.open}`);
  if (counts.blocked) parts.push(`🟡 ${counts.blocked}`);
  return parts.length ? ` — ${parts.join(" · ")}` : "";
}

function formatRelative(targetMs: number, nowMs: number): string {
  const days = Math.round((targetMs - nowMs) / DAY_MS);
  if (days === 0) return "today";
  if (days === 1) return "tomorrow";
  if (days === -1) return "yesterday";
  if (days > 0) return `in ${days}d`;
  return `${-days}d ago`;
}

function shortDisplayId(id: string): string {
  return id.slice(0, 18);
}

function truncate(value: string, length: number): string {
  return value.length > length ? `${value.slice(0, length - 1)}…` : value;
}
