#!/usr/bin/env bun
/**
 * Put a working-tree build on PATH as `tasq-dev`, beside the published `tasq`.
 *
 * Nothing documented how to dogfood your own build. The choices were running
 * `bun packages/tasq-cli/src/index.ts` by hand, or overwriting the installed
 * binary and losing the published reference - and the second is what produced
 * a hand-written launcher on this machine, which worked, lived nowhere, and
 * nobody could have recreated.
 *
 * The shape below is that launcher's, because its design was right: it runs
 * the BUILT artifact rather than source, so what is dogfooded resembles what
 * ships; and it fails loudly with exit 3 and an actionable line rather than
 * leaking a runtime stack trace from inside a tool the operator believes is
 * Tasq. This only makes it reproducible.
 *
 * The published `tasq` is never touched. It stays the acquisition reference,
 * so "does this work for someone who installed it" remains answerable at any
 * moment, and a dev build cannot quietly become the thing being dogfooded.
 * The migration receipt records which of the two wrote to a store, because
 * they are not interchangeable writers.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

const MARKER = "Generated by `pnpm dev:link`";
const productRoot = resolve(import.meta.dir, "..");
const build = join(productRoot, "dist/cli/index.js");
const binDir = join(homedir(), ".local", "bin");
const shimPath = join(binDir, "tasq-dev");
const force = process.argv.includes("--force");

const shim = `#!/bin/sh
# ${MARKER}. Runs the working tree's build, never the published one.
set -eu
REPO="${productRoot}"
BUILD="${build}"
if [ ! -d "$REPO/.git" ]; then
  printf '%s\\n' "tasq-dev: the checkout this shim points at is gone: $REPO" >&2
  printf '%s\\n' "tasq-dev: re-run \\\`pnpm dev:link\\\` from a live checkout, or delete ${shimPath}" >&2
  exit 3
fi
if [ ! -f "$BUILD" ]; then
  printf '%s\\n' "tasq-dev: no local build at $BUILD" >&2
  printf '%s\\n' "tasq-dev: run \\\`pnpm build:cli\\\` in $REPO" >&2
  exit 3
fi
exec "$BUILD" "$@"
`;

if (process.argv.includes("--print")) {
  process.stdout.write(shim);
  process.exit(0);
}

mkdirSync(binDir, { recursive: true });
if (existsSync(shimPath) && !force) {
  const existing = readFileSync(shimPath, "utf8");
  // Refuse to displace anything this script did not write. A dev tool that
  // overwrites what an operator put there by hand is the failure this exists
  // to prevent, one directory over.
  if (!existing.includes(MARKER)) {
    process.stderr.write(
      `tasq-dev: ${shimPath} exists and this script did not write it.\n`
      + "Inspect it, then re-run with --force to replace it.\n",
    );
    process.exit(1);
  }
}
writeFileSync(shimPath, shim, { encoding: "utf8", mode: 0o755 });
chmodSync(shimPath, 0o755);

process.stdout.write(`${JSON.stringify({
  contractVersion: "tasq.dev-link.v1",
  shim: shimPath,
  runs: build,
  buildWith: "pnpm build:cli",
  publishedBinaryUntouched: join(binDir, "tasq"),
  buildPresent: existsSync(build),
  ok: true,
}, null, 2)}\n`);
