#!/usr/bin/env bash
# Install the tasq CLI into PATH as a Bun-launched script.
#
# Usage:
#   ./scripts/install-cli.sh                 # default: ~/.local/bin/tasq
#   ./scripts/install-cli.sh /usr/local/bin  # custom install dir
#
# Why a launcher script (not a `bun --compile` standalone binary)?
#
#   @libsql/client requires a platform-specific native module (.node)
#   that Bun's `--compile` cannot fully bundle today. The launcher
#   approach uses Bun + node_modules in-place — works perfectly on the
#   machine where you installed, and is trivially debuggable.
#
#   Migration to a true standalone binary is tracked for v0.2+ once we
#   either (a) move to `bun:sqlite`, or (b) Bun ships proper native-addon
#   bundling.
#
# Re-running this script is idempotent (it just rewrites the launcher).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI_ENTRY="$REPO_ROOT/packages/tasq-cli/src/index.ts"
BIN_NAME="tasq"

INSTALL_DIR="${1:-$HOME/.local/bin}"
TARGET="$INSTALL_DIR/$BIN_NAME"

if ! command -v bun >/dev/null 2>&1; then
  echo "error: bun is required (https://bun.sh)" >&2
  exit 1
fi

if [ ! -f "$CLI_ENTRY" ]; then
  echo "error: CLI entry not found at $CLI_ENTRY" >&2
  exit 1
fi

echo "→ Verifying CLI runs"
bun run "$CLI_ENTRY" version >/dev/null

echo "→ Installing launcher at $TARGET"
mkdir -p "$INSTALL_DIR"

# The launcher checks its own target before exec'ing. A diagnostic that lives
# inside the running CLI cannot fire when the CLI is what fails to start, and
# a launcher outliving its checkout is the likely end state: the directory gets
# deleted, moved, or its node_modules go stale, and the user meets a raw
# runtime error naming a module instead of the stale path they need to fix.
cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# tasq launcher - generated by scripts/install-cli.sh
# Re-run install-cli.sh to regenerate.
set -u
TASQ_ENTRY="$CLI_ENTRY"
TASQ_REPO="$REPO_ROOT"

if [ ! -f "\$TASQ_ENTRY" ]; then
  echo "tasq: this launcher points at a checkout that is gone." >&2
  echo "  launcher: \$0" >&2
  echo "  expected: \$TASQ_ENTRY" >&2
  echo "  Remove this launcher, or reinstall from a live checkout with scripts/install-cli.sh." >&2
  echo "  For the published release: https://tasq.run/install.sh" >&2
  exit 3
fi
if ! command -v bun >/dev/null 2>&1; then
  echo "tasq: bun is required by this launcher and was not found (https://bun.sh)." >&2
  echo "  launcher: \$0" >&2
  exit 3
fi
if [ ! -d "\$TASQ_REPO/node_modules" ]; then
  echo "tasq: this launcher's checkout has no installed dependencies." >&2
  echo "  checkout: \$TASQ_REPO" >&2
  echo "  Run 'pnpm install --frozen-lockfile' there, or remove this launcher." >&2
  exit 3
fi
exec bun run "\$TASQ_ENTRY" "\$@"
EOF
chmod +x "$TARGET"

echo ""
echo "✓ Installed: $TARGET"
echo "  Entry point: $CLI_ENTRY"
echo ""
echo "Add $INSTALL_DIR to your PATH if not already:"
echo "  export PATH=\"$INSTALL_DIR:\$PATH\""
echo ""
echo "Then verify:"
echo "  tasq version"
