#!/usr/bin/env bash
# Install the tasq CLI into PATH as a Bun-launched script.
#
# Usage:
#   ./scripts/install-cli.sh                 # default: ~/.local/bin/tasq
#   ./scripts/install-cli.sh /usr/local/bin  # custom install dir
#
# Why a launcher script (not a `bun --compile` standalone binary)?
#
#   @libsql/client requires a platform-specific native module (.node)
#   that Bun's `--compile` cannot fully bundle today. The launcher
#   approach uses Bun + node_modules in-place — works perfectly on the
#   machine where you installed, and is trivially debuggable.
#
#   Migration to a true standalone binary is tracked for v0.2+ once we
#   either (a) move to `bun:sqlite`, or (b) Bun ships proper native-addon
#   bundling.
#
# Re-running this script is idempotent (it just rewrites the launcher).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI_ENTRY="$REPO_ROOT/packages/tasq-cli/src/index.ts"
BIN_NAME="tasq"

INSTALL_DIR="${1:-$HOME/.local/bin}"
TARGET="$INSTALL_DIR/$BIN_NAME"

if ! command -v bun >/dev/null 2>&1; then
  echo "error: bun is required (https://bun.sh)" >&2
  exit 1
fi

if [ ! -f "$CLI_ENTRY" ]; then
  echo "error: CLI entry not found at $CLI_ENTRY" >&2
  exit 1
fi

echo "→ Verifying CLI runs"
bun run "$CLI_ENTRY" version >/dev/null

echo "→ Installing launcher at $TARGET"
mkdir -p "$INSTALL_DIR"

cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# tasq launcher — generated by scripts/install-cli.sh
# Re-run install-cli.sh to regenerate.
exec bun run "$CLI_ENTRY" "\$@"
EOF
chmod +x "$TARGET"

echo ""
echo "✓ Installed: $TARGET"
echo "  Entry point: $CLI_ENTRY"
echo ""
echo "Add $INSTALL_DIR to your PATH if not already:"
echo "  export PATH=\"$INSTALL_DIR:\$PATH\""
echo ""
echo "Then verify:"
echo "  tasq version"
