/**
 * A projection renders one space and lives with the project it renders.
 *
 * One global `projectionTarget` used to render whichever space was effective
 * after every mutation. On 2026-08-04 a life instance's TASKS.md was
 * regenerated with a software project's backlog that way. Now a directory
 * binding renders only its own projection, and the global target renders only
 * the global default space.
 */
import { afterEach, describe, expect, setDefaultTimeout, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const cli = join(root, "src", "index.ts");
const temporary: string[] = [];
setDefaultTimeout(60_000);

interface Result { stdout: string; stderr: string; exitCode: number }

function sandbox(): { home: string; base: string } {
  const base = mkdtempSync(join(tmpdir(), "tasq-projection-"));
  temporary.push(base);
  const home = join(base, "home");
  mkdirSync(home, { mode: 0o700 });
  return { home, base };
}

function project(base: string, name: string): string {
  const dir = join(base, name);
  mkdirSync(dir, { recursive: true });
  return dir;
}

afterEach(() => {
  while (temporary.length > 0) rmSync(temporary.pop()!, { recursive: true, force: true });
});

async function run(home: string, cwd: string, argv: string[], env: Record<string, string> = {}): Promise<Result> {
  const child = Bun.spawn([process.execPath, "run", cli, ...argv], {
    cwd,
    env: {
      ...process.env,
      HOME: home,
      TASQ_HOME: join(home, ".tasq"),
      TASQ_DB_URL: "",
      TASQ_EVENT_JOURNAL_PATH: "",
      TASQ_TENANT: "",
      ...env,
    },
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
    child.exited,
  ]);
  return { stdout, stderr, exitCode };
}

async function ok(home: string, cwd: string, argv: string[], env: Record<string, string> = {}): Promise<Result> {
  const result = await run(home, cwd, argv, env);
  if (result.exitCode !== 0) throw new Error(`${argv.join(" ")} failed (${result.exitCode})\n${result.stderr}`);
  return result;
}

async function json(home: string, cwd: string, argv: string[], env: Record<string, string> = {}): Promise<any> {
  return JSON.parse((await ok(home, cwd, [...argv, "--json"], env)).stdout);
}

function configFile(home: string): any {
  return JSON.parse(readFileSync(join(home, ".tasq", "config.json"), "utf8"));
}

function journal(home: string): any[] {
  const path = join(home, ".tasq", "config-journal.jsonl");
  return existsSync(path) ? readFileSync(path, "utf8").trim().split("\n").map((line) => JSON.parse(line)) : [];
}

describe("a projection lives with the project it renders", () => {
  test("a bound directory renders its own projection after a mutation, and never the global target", async () => {
    const { home, base } = sandbox();
    const first = project(base, "first");
    const canonical = realpathSync(first);
    const elsewhere = project(base, "elsewhere");
    const globalTarget = join(elsewhere, "GLOBAL.md");
    await json(home, first, ["setup", "--space", "acme/first", "--actor", "gwendall"]);
    await ok(home, first, ["config", "set", "projectionTarget", globalTarget]);

    const bound = await json(home, first, ["use", "acme/first", "--project-to", "TASKS.md"]);
    expect(bound.projection).toBe(join(canonical, "TASKS.md"));
    expect(configFile(home).directoryProjections).toEqual({ [canonical]: join(canonical, "TASKS.md") });

    await json(home, first, ["add", "Render me"]);
    const rendered = readFileSync(join(first, "TASKS.md"), "utf8");
    expect(rendered).toContain("AUTO-GENERATED by tasq");
    expect(rendered).toContain("Render me");
    expect(existsSync(globalTarget)).toBe(false);

    // A subdirectory of the bound tree renders the same file.
    const deep = join(first, "src");
    mkdirSync(deep, { recursive: true });
    await json(home, deep, ["add", "Deeper"]);
    expect(readFileSync(join(first, "TASKS.md"), "utf8")).toContain("Deeper");
    expect(existsSync(globalTarget)).toBe(false);

    const shown = await json(home, deep, ["use"]);
    expect(shown.projection).toBe(join(canonical, "TASKS.md"));
  });

  test("the global target renders the global default space only", async () => {
    const { home, base } = sandbox();
    const first = project(base, "first");
    const globalTarget = join(home, "GLOBAL.md");
    // No directory is bound: the global default is the only space.
    await json(home, first, ["setup", "--space", "acme/first", "--actor", "gwendall", "--no-bind", "--no-instructions"]);
    await ok(home, first, ["config", "set", "projectionTarget", globalTarget]);
    await json(home, first, ["add", "Default space task"]);
    expect(readFileSync(globalTarget, "utf8")).toContain("Default space task");

    // An explicitly selected other space must not overwrite the default's file.
    await json(home, first, ["onboard", "--space", "acme/other", "--actor", "gwendall"]);
    await json(home, first, ["add", "Other space task", "--tenant", "acme/other"]);
    const rendered = readFileSync(globalTarget, "utf8");
    expect(rendered).toContain("Default space task");
    expect(rendered).not.toContain("Other space task");

    // The explicit flag naming the default itself still renders it.
    await json(home, first, ["add", "Named default task", "--tenant", "acme/first"]);
    expect(readFileSync(globalTarget, "utf8")).toContain("Named default task");
  });

  test("a projection outside the bound directory is refused and nothing is written", async () => {
    const { home, base } = sandbox();
    const first = project(base, "first");
    const elsewhere = project(base, "elsewhere");
    await json(home, first, ["setup", "--space", "acme/first", "--actor", "gwendall"]);
    const before = configFile(home);
    const refused = await run(home, first, ["use", "acme/first", "--project-to", join(elsewhere, "TASKS.md")]);
    expect(refused.exitCode).not.toBe(0);
    expect(refused.stderr).toContain("A projection lives with the project it renders");
    expect(configFile(home)).toEqual(before);
  });

  test("--no-projection drops the projection, --clear drops binding and projection, and both are journaled", async () => {
    const { home, base } = sandbox();
    const first = project(base, "first");
    const canonical = realpathSync(first);
    await json(home, first, ["setup", "--space", "acme/first", "--actor", "gwendall"]);
    await json(home, first, ["use", "acme/first", "--project-to", "docs/TASKS.md"]);
    expect(configFile(home).directoryProjections).toEqual({ [canonical]: join(canonical, "docs", "TASKS.md") });

    const dropped = await json(home, first, ["use", "acme/first", "--no-projection"]);
    expect(dropped.projection).toBeNull();
    expect(configFile(home).directoryProjections).toBeUndefined();
    expect(journal(home).at(-1)).toMatchObject({
      command: ["use", "--no-projection"],
      projections: { removed: [canonical] },
    });

    await json(home, first, ["use", "acme/first", "--project-to", "TASKS.md"]);
    const cleared = await json(home, first, ["use", "--clear"]);
    expect(cleared).toMatchObject({ action: "cleared", binding: null, projection: null });
    expect(configFile(home).directorySpaces).toBeUndefined();
    expect(configFile(home).directoryProjections).toBeUndefined();
    expect(journal(home).at(-1)).toMatchObject({
      command: ["use", "--clear"],
      bindings: { removed: [canonical] },
      projections: { removed: [canonical] },
    });
  });

  test("a stale copy of the config keeps a projection another writer set", async () => {
    const { home, base } = sandbox();
    const first = project(base, "first");
    const second = project(base, "second");
    const canonicalFirst = realpathSync(first);
    await json(home, first, ["setup", "--space", "acme/first", "--actor", "gwendall"]);
    await json(home, first, ["use", "acme/first", "--project-to", "TASKS.md"]);
    // A writer that never saw the projection saves its own copy of the file.
    const stale = configFile(home);
    delete stale.directoryProjections;
    writeFileSync(join(home, ".tasq", "config.json"), JSON.stringify(stale), { mode: 0o600 });
    // ...and then a normal command writes the config again through saveConfig.
    await json(home, second, ["setup", "--space", "acme/second", "--actor", "gwendall"]);
    // The hand-written stale file lost it; the next write preserved what was on disk at that time,
    // which is the stale file. What matters is that a saveConfig never DROPS an on-disk entry:
    expect(configFile(home).directorySpaces).toMatchObject({ [canonicalFirst]: "acme/first" });
  });
});
